gordolab/urls.py
"""Defines URL patterns for gordos."""

from django.urls import path
from . import views


app_name = 'gordolab'
urlpatterns =[
    #Home page
    path('', views.index, name='index'),
    #Page that show project gordofut
    path('gordofut/', views.gordofut, name= 'gordofut'),
    #Page that show about us
    path('quienessomos/', views.quienessomos, name= 'quienessomos'),

    

        
]

gordolab_org/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gordolab.urls'))
]

gordolab/models.py
from django.db import models

# Create your models here.

gordolab/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    """Home page for gordolab"""
    return render(request, 'gordolab/index.html')

def gordofut(request):
    """Home page for gordofut"""
    return render(request, 'gordolab/gordofut.html')

def quienessomos(request):
    """information about us"""
    return render(request, 'gordolab/quienessomos.html')

gordolab/templates/gordolab/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gordolab</title>
<!--Bootstrap css-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet"  href="{% static 'css/style.css' %}">
 <body>
<!--barra de navegación-->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top ">
  <a class="navbar-brand" href="{% url 'gordolab:index'%}"><img src="{% static 'gordolab.png' %} " width="50">Gordolab</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active" href="{% url 'gordolab:gordofut'%}">Gordofut</a>
      <a class="nav-link" href="{% url 'gordolab:quienessomos'%}">Quienes somos</a>
    </div>
  </div>
</nav>

<!--Contenido-->
<main class="container">
 <div class="pb-2 nb-2 border-bottom">
     {% block page_header %}{% endblock page_header %}

     {% block content %}
     
     

     {% endblock content %}
 </div>



</main>

<footer>
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12 segment-one">
          <h3>Redes</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis enim sed minima rerum ratione fugiat delectus possimus perspiciatis illo, officiis iusto omnis maiores odit nam soluta quidem aliquid ex. Fugit.</p>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12 segment-two">
          <h3>Redes amigas</h3>
          <ul>
            <li><a href="#"></a>Evento</li>
            <li><a href="#"></a>LA farra</li>
            <li><a href="#"></a>Hattrick</li>
            <li><a href="#"></a>Gordobeses</li>
          </ul>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12 segment-three">
          <h2>Follow us</h2>
          <p>Please follo Lorem ipsum dolor sit amet consectetur adipisicing elit. In, doloribus eligendi? Animi numquam laborum, veritatis enim soluta officiis labore tenetur saepe commodi sunt culpa vitae esse! At aliquam facilis voluptas?
            <a href="H"><i class="fa-fa-facebook"></a>

          </p>
        </div>


        
      </div>

    </div>
  </div>

</footer>

<!--jquery y demases-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

gordolab/templates/gordolab/gordofut.html
{% extends "gordolab/base.html" %}

{% block content %}

{% endblock content%}

gordolab/templates/gordolab/index.html
{% extends "gordolab/base.html" %}
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

 {% block page_header %}

  <!--Jumbotron-->
<div class="jumbotron jumbotron-fluid mt-5 rounded-0 ">
  <H1 class="display-3"> GORDOLAB</H1> 
  <div class="d-flex">
  <img src="static/gordolab.png" width="100" class="img-fluid">
  <p class="lead"><b>Fabricamos</b> proyectos tecnológicos con metodologías innovadoras, generando <b>prototipos</b>funcionales y <b>aprendizajes sistematizados</b></p>
</div>
<hr class="my-3">

<div class="d-flex justify-content-between align-items-center">
  <p>Somos gordolab, conoce a nuestro equipo de trabajo</p>

 <a class="btn btn-lg btn-primary" href="{% url 'gordolab:quienessomos'%}"
   role="button"> Conócenos </a> 

</div>

</div>


{% endblock page_header %}
</head>
<body>

{% block content %}

<header class= "container">
  <div class="row">
    
    <div class="col-6 fluid">
      <h4>¿Cómo lo hacemos?</h4>
      <h5 class="text-justify">En la de era de la cuarta revolución industrial, aprovechamos y promovemos la democratización de la tecnología para crear soluciones (productos y servicios) que generen valor</h5>
      <p class="text-justify">Para lograrlo, generamos proyectos en base a prototipos funcionales y escalables. Combinamos la gestión de proyectos, metodologías de innovación, la ciencia de datos, las tecnologías y el pensamiento sistémico para crear proyectos digitales</p>
    </div>
    <div class="col-6 text-center">
      <img src="static/header.png" class="img-fluid">
    </div>

  </div>
</header>

<div class="container my-4">
 <div class="row">
   <div class="col-12">
     <h4>¿Por qué lo hacemos?</h4>
     <p class="text-justify">Creemos en la creación de un futuro sostenible y distribuido, por eso buscamos generar soluciones digitales locales de bajo costo a problemas cotidianos.</p>
     <img src="static/foto.jpg" class="img-fluid">
     <img src="{% static 'pepe.jpeg' %}"
   </div>

 </div>
</div>


   



{% endblock content%}
  
</body>
</html>



<!--css-->

gordolab/templates/gordolab/quienessomos.html
{% extends "gordolab/base.html" %}
{% load static %}

{% block content %}

<div class="container my-5">
  <div class="row">
    <div class="media">
      <img src="{% static 'gordolab.png' %}" class="mr-3" alt="...">
      <div class="media-body">
        <p class="text-justify-center">Somos un grupo de amigos ingenieros unidos por la pasión del fútbol y la tecnología. nuestro propósito es generar soluciones digitales locales de bajo costo.</p>
      </div>
    </div>
</div>
 
<div class="container my-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'pepe.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
              </div>
        

        </div>
        <div class="col-4">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                  <div class="col-md-4">
                    <img src="{% static 'Simon.jpeg' %}" class="card-img" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">Card title</h5>
                      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>
                  </div>
                </div>
              </div>

        </div>
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'Cristian.jpeg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                </div>
           </div>
        </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-4">
          <div class="card">
            <img src="{% static 'pablo.jpeg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
        <div class="col-4">
        <div class="card">
          <img src="{% static 'diego.jpeg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock content%}